import React, { createContext, useContext, useState, useCallback } from 'react';

export type SupportedLanguage = 'english' | 'setswana' | 'french' | 'twi' | 'ewe' | 'fante' | 'ga';

interface LanguageContextType {
  interfaceLanguage: SupportedLanguage;
  responseLanguage: SupportedLanguage;
  setInterfaceLanguage: (lang: SupportedLanguage) => void;
  setResponseLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const UI_TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  english: {
    // Sidebar / ConversationList
    newChat: 'New chat',
    search: 'Search',
    settings: 'Settings',
    today: 'Today',
    yesterday: 'Yesterday',
    older: 'Older',
    signOut: 'Sign out',
    searchPlaceholder: 'Search conversations...',
    noConversationsFound: 'No conversations found matching',
    searchResults: 'Search Results',
    greyedTeach: 'GreyEd Teach',
    uDocs: 'U Docs',
    adminDashboard: 'Admin Dashboard',
    supaAdmin: 'Supa Admin',
    websiteBuilder: 'Website Builder',
    rename: 'Rename',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    // Settings Modal tabs & labels
    account: 'Account',
    language: 'Language',
    privacy: 'Privacy',
    help: 'Help',
    upgrade: 'Upgrade',
    subscription: 'Subscription',
    accountSettings: 'Account Settings',
    name: 'Name',
    email: 'Email',
    changePassword: 'Change Password',
    change: 'Change',
    yourAccountEmail: 'Your account email address',
    updateYourAccount: 'Update your account password',
    languageSettings: 'Language Settings',
    interfaceLanguage: 'Interface Language',
    controlsMenus: 'Controls the language of menus and messages',
    defaultResponse: 'Default Response Language',
    uhuruWillRespond: 'Uhuru will respond in this language by default',
    helpSupport: 'Help & Support',
    contactSupport: 'Contact Support',
    needHelp: 'Need help? Our support team is ready to assist you.',
    contactUs: 'Contact Support',
    frequentlyAsked: 'Frequently Asked Questions',
    noFaqsFound: 'No FAQs found matching',
    tryDifferent: 'Try a different search term',
    aboutUhuru: 'About Uhuru',
    version: 'Version',
    madeWith: 'Made with',
    botswana: 'in Botswana',
    saveChanges: 'Save Changes',
    settingsSaved: 'Settings saved',
    searchFaqs: 'Search FAQs...',
    close: 'Close',
    // Chat Input
    image: 'Image',
    upload: 'Upload',
    askMeAnything: 'Ask me anything...',
    describeImage: 'Describe the image you want to create',
    editingMessage: 'Editing',
    micAccess: 'Microphone Access Required',
    docLimit: 'Document Limit',
  },
  setswana: {
    newChat: 'Puisano e ntšha',
    search: 'Batla',
    settings: 'Ditlhophiso',
    today: 'Gompieno',
    yesterday: 'Maabane',
    older: 'Bogologolo',
    signOut: 'Tswa',
    searchPlaceholder: 'Batla dipuisano...',
    noConversationsFound: 'Ga go na dipuisano tse di bonweng tse di tsamaelanang le',
    searchResults: 'Diphitlhelelo tsa Patlisiso',
    greyedTeach: 'GreyEd Teach',
    uDocs: 'U Docs',
    adminDashboard: 'Tafolokgolo ya Motsamaisi',
    supaAdmin: 'Supa Admin',
    websiteBuilder: 'Sebopiwa sa Websaete',
    rename: 'Fetola leina',
    delete: 'Phimola',
    save: 'Boloka',
    cancel: 'Khansela',
    account: 'Akhaonto',
    language: 'Puo',
    privacy: 'Sephiri',
    help: 'Thuso',
    upgrade: 'Tokafatsa',
    subscription: 'Peeletso',
    accountSettings: 'Ditlhophiso tsa Akhaonto',
    name: 'Leina',
    email: 'Imeile',
    changePassword: 'Fetola Khunololamoraba',
    change: 'Fetola',
    yourAccountEmail: 'Aterese ya imeile ya akhaonto ya gago',
    updateYourAccount: 'Fetola khunololamoraba ya akhaonto ya gago',
    languageSettings: 'Ditlhophiso tsa Puo',
    interfaceLanguage: 'Puo ya Tirisano',
    controlsMenus: 'Se se laola puo ya dimenu le melaetsa',
    defaultResponse: 'Puo ya Dikarabo tsa Tlwaelo',
    uhuruWillRespond: 'Uhuru e tla araba ka puo e ka tlwaelo',
    helpSupport: 'Thuso & Tshegetso',
    contactSupport: 'Ikgolaganye le Thuso',
    needHelp: 'O tlhoka thuso? Setlhopha sa rona sa thuso se ipaakanyeditse go go thusa.',
    contactUs: 'Ikgolaganye le Thuso',
    frequentlyAsked: 'Dipotso tse Di Botswang Gantsi',
    noFaqsFound: 'Ga go na dipotso tse di bonweng tse di tsamaelanang le',
    tryDifferent: 'Leka lefoko le lengwe la patlisiso',
    aboutUhuru: 'Ka ga Uhuru',
    version: 'Mofuta',
    madeWith: 'E dirilwe ka',
    botswana: 'kwa Botswana',
    saveChanges: 'Boloka Diphetogo',
    settingsSaved: 'Ditlhophiso di bolokegile',
    searchFaqs: 'Batla Dipotso...',
    close: 'Tswala',
    image: 'Seswantshο',
    upload: 'Tukusa',
    askMeAnything: 'Botsa se sefe...',
    describeImage: 'Tlhalosa seswantshο se o batlang go se bopa',
    editingMessage: 'Go Fetola',
    micAccess: 'Go Tlhoka Tumelo ya Maekherofono',
    docLimit: 'Molemo wa Tokumente',
  },
  french: {
    newChat: 'Nouvelle discussion',
    search: 'Rechercher',
    settings: 'Paramètres',
    today: "Aujourd'hui",
    yesterday: 'Hier',
    older: 'Plus anciens',
    signOut: 'Se déconnecter',
    searchPlaceholder: 'Rechercher des discussions...',
    noConversationsFound: 'Aucune discussion trouvée pour',
    searchResults: 'Résultats de recherche',
    greyedTeach: 'GreyEd Teach',
    uDocs: 'U Docs',
    adminDashboard: 'Tableau de bord admin',
    supaAdmin: 'Supa Admin',
    websiteBuilder: 'Créateur de site web',
    rename: 'Renommer',
    delete: 'Supprimer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    account: 'Compte',
    language: 'Langue',
    privacy: 'Confidentialité',
    help: 'Aide',
    upgrade: 'Améliorer',
    subscription: 'Abonnement',
    accountSettings: 'Paramètres du compte',
    name: 'Nom',
    email: 'Email',
    changePassword: 'Changer le mot de passe',
    change: 'Changer',
    yourAccountEmail: "L'adresse email de votre compte",
    updateYourAccount: 'Mettez à jour le mot de passe de votre compte',
    languageSettings: 'Paramètres de langue',
    interfaceLanguage: "Langue d'interface",
    controlsMenus: 'Contrôle la langue des menus et des messages',
    defaultResponse: 'Langue de réponse par défaut',
    uhuruWillRespond: 'Uhuru répondra dans cette langue par défaut',
    helpSupport: 'Aide & Support',
    contactSupport: 'Contacter le support',
    needHelp: "Besoin d'aide? Notre équipe de support est prête à vous aider.",
    contactUs: 'Contacter le support',
    frequentlyAsked: 'Questions fréquemment posées',
    noFaqsFound: 'Aucune FAQ trouvée pour',
    tryDifferent: 'Essayez un autre terme de recherche',
    aboutUhuru: "À propos d'Uhuru",
    version: 'Version',
    madeWith: 'Fait avec',
    botswana: 'au Botswana',
    saveChanges: 'Enregistrer les modifications',
    settingsSaved: 'Paramètres enregistrés',
    searchFaqs: 'Rechercher FAQ...',
    close: 'Fermer',
    image: 'Image',
    upload: 'Télécharger',
    askMeAnything: "Demandez-moi n'importe quoi...",
    describeImage: "Décrivez l'image que vous souhaitez créer",
    editingMessage: 'Modification',
    micAccess: 'Accès au microphone requis',
    docLimit: 'Limite de documents',
  },
  twi: {
    newChat: 'Nsɛm foforɔ',
    search: 'Hwehwɛ',
    settings: 'Nhyehyɛe',
    today: 'Ɛnnɛ',
    yesterday: 'Ɛnnɛ twaa so',
    older: 'Tete',
    signOut: 'Pue fii',
    searchPlaceholder: 'Hwehwɛ nsɛm...',
    noConversationsFound: 'Ɛnnhuu nsɛm biara a ɛfa',
    searchResults: 'Hwehwɛ Nneɛma',
    greyedTeach: 'GreyEd Teach',
    uDocs: 'U Docs',
    adminDashboard: 'Adminfoo Nhyehyɛe',
    supaAdmin: 'Supa Admin',
    websiteBuilder: 'Website Siesie',
    rename: 'Din foforɔ',
    delete: 'Yi firi hɔ',
    save: 'Sie',
    cancel: 'Gyae',
    account: 'Akaunti',
    language: 'Kasa',
    privacy: 'Ɔhintabea',
    help: 'Boa',
    upgrade: 'Ma yɛn soa',
    subscription: 'Ntoatoaso',
    accountSettings: 'Akaunti Nhyehyɛe',
    name: 'Din',
    email: 'Imeila',
    changePassword: 'Sesa w\'asensam',
    change: 'Sesa',
    yourAccountEmail: 'Wo akaunti imeila',
    updateYourAccount: 'Yi wo akaunti asensam foforɔ',
    languageSettings: 'Kasa Nhyehyɛe',
    interfaceLanguage: 'Interface Kasa',
    controlsMenus: 'Ɛhyɛ menu ne nkra kasa ase',
    defaultResponse: 'Kasa a Uhuru bɛfa ato so',
    uhuruWillRespond: 'Uhuru bɛfa kasa yi ato wo so',
    helpSupport: 'Boa & Nkuran',
    contactSupport: 'Ka kyerɛ Boa Ntɛm',
    needHelp: 'Wohia boa? Yɛn boa nnipa no wɔ hɔ.',
    contactUs: 'Ka kyerɛ yɛn',
    frequentlyAsked: 'Nsɛm a Wɔhwehwɛ Wɔn Pii',
    noFaqsFound: 'Ɛnnhuu nsɛm biara a ɛfa',
    tryDifferent: 'Hwehwɛ biribi foforɔ',
    aboutUhuru: 'Fa Uhuru ho',
    version: 'Nkrataa',
    madeWith: 'Yɛdii ne',
    botswana: 'Botswana',
    saveChanges: 'Sie nsakrae no',
    settingsSaved: 'Wosii nhyehyɛe no',
    searchFaqs: 'Hwehwɛ Nsɛm...',
    close: 'To mu',
    image: 'Mfonini',
    upload: 'Fa kɔ',
    askMeAnything: 'Bisa me biribiara...',
    describeImage: 'Kyerɛ mfonini a wohia no',
    editingMessage: 'Sesa',
    micAccess: 'Hia Maekherofono',
    docLimit: 'Tokumente Dodow',
  },
  ewe: {
    newChat: 'Ɖoɖo yeye',
    search: 'Saɖe',
    settings: 'Ɖoɖowo',
    today: 'Egbe',
    yesterday: 'Etsɔ',
    older: 'Gbã tɔtrɔ',
    signOut: 'Yi egbe',
    searchPlaceholder: 'Saɖe ɖoɖowo...',
    noConversationsFound: 'Ɖoɖo aɖeke mefoa o dzi',
    searchResults: 'Saɖe Ŋutinya',
    greyedTeach: 'GreyEd Teach',
    uDocs: 'U Docs',
    adminDashboard: 'Admin Ɖoɖo',
    supaAdmin: 'Supa Admin',
    websiteBuilder: 'Website Wɔla',
    rename: 'Ŋkɔ yeye',
    delete: 'Ɖe',
    save: 'Dzra',
    cancel: 'Ɖe ɖe eme',
    account: 'Akaunti',
    language: 'Gbegbɔgblɔ',
    privacy: 'Nuwɔwɔ ƒe nuku',
    help: 'Kpekpeɖeŋu',
    upgrade: 'Ɖe wu',
    subscription: 'Ɖoɖo',
    accountSettings: 'Akaunti ƒe ɖoɖowo',
    name: 'Ŋkɔ',
    email: 'Imeila',
    changePassword: 'Trɔ mɔ',
    change: 'Trɔ',
    yourAccountEmail: 'Wò akaunti imeila',
    updateYourAccount: 'Ɖe wò akaunti mɔ fofo ŋu',
    languageSettings: 'Gbegbɔgblɔ ƒe ɖoɖowo',
    interfaceLanguage: 'Interface gbegbɔgblɔ',
    controlsMenus: 'Edzi menu kple ŋɔli gbegbɔgblɔ ŋu',
    defaultResponse: 'Gbegbɔgblɔ si Uhuru nate ŋu gblɔ ame',
    uhuruWillRespond: 'Uhuru ate ŋu gblɔ ame gbegbɔgblɔ sia me',
    helpSupport: 'Kpekpeɖeŋu & Kpekpe',
    contactSupport: 'Ɖo kpɔ Kpekpe',
    needHelp: 'Ehia kpekpeɖeŋu? Yewo ƒe kpekpe ƒe kpoe lolo la wo le afɔm.',
    contactUs: 'Ɖo kpɔ yɛwo',
    frequentlyAsked: 'Nusɔsɔwo si wɔƒle vevie',
    noFaqsFound: 'Nusɔsɔ aɖeke mefoa o dzi',
    tryDifferent: 'Saɖe nubabla fofo',
    aboutUhuru: 'Uhuru fa',
    version: 'Nkɔ',
    madeWith: 'Wowɔe kple',
    botswana: 'Botswana',
    saveChanges: 'Dzra tròtròwo',
    settingsSaved: 'Woɖo ɖoɖowo ɖe eme',
    searchFaqs: 'Saɖe Nusɔsɔwo...',
    close: 'Xe',
    image: 'Nutataŋu',
    upload: 'Ɖe ŋu',
    askMeAnything: 'Bɔ nubabla bibia dom...',
    describeImage: 'Ŋlɔ nutataŋu si hia',
    editingMessage: 'Trɔ',
    micAccess: 'Hia Maekherofono',
    docLimit: 'Sɔsɔ Kadodo',
  },
  fante: {
    newChat: 'Nsɛm foforɔ',
    search: 'Hwehwɛ',
    settings: 'Nhyehyɛe',
    today: 'Ndɛ',
    yesterday: 'Ndɛ a etwa to',
    older: 'Tete',
    signOut: 'Pue',
    searchPlaceholder: 'Hwehwɛ nsɛm...',
    noConversationsFound: 'Ɛnnhuu nsɛm biara a ɛfa',
    searchResults: 'Hwehwɛ Nneɛma',
    greyedTeach: 'GreyEd Teach',
    uDocs: 'U Docs',
    adminDashboard: 'Admin Nhyehyɛe',
    supaAdmin: 'Supa Admin',
    websiteBuilder: 'Website Siesie',
    rename: 'Din foforɔ',
    delete: 'Yi firi hɔ',
    save: 'Sie',
    cancel: 'Gyae',
    account: 'Akaunti',
    language: 'Kasa',
    privacy: 'Ɔhintabea',
    help: 'Boa',
    upgrade: 'Ma yɛn soa',
    subscription: 'Ntoatoaso',
    accountSettings: 'Akaunti Nhyehyɛe',
    name: 'Din',
    email: 'Imeila',
    changePassword: 'Sesa w\'asensam',
    change: 'Sesa',
    yourAccountEmail: 'Wo akaunti imeila',
    updateYourAccount: 'Yi wo akaunti asensam foforɔ',
    languageSettings: 'Kasa Nhyehyɛe',
    interfaceLanguage: 'Interface Kasa',
    controlsMenus: 'Ɛhyɛ menu ne nkra kasa ase',
    defaultResponse: 'Kasa a Uhuru bɛfa ato so',
    uhuruWillRespond: 'Uhuru bɛfa kasa yi ato wo so',
    helpSupport: 'Boa & Nkuran',
    contactSupport: 'Ka kyerɛ Boa Ntɛm',
    needHelp: 'Wohia boa? Yɛn boa nnipa no wɔ hɔ.',
    contactUs: 'Ka kyerɛ yɛn',
    frequentlyAsked: 'Nsɛm a Wɔhwehwɛ Wɔn Pii',
    noFaqsFound: 'Ɛnnhuu nsɛm biara a ɛfa',
    tryDifferent: 'Hwehwɛ biribi foforɔ',
    aboutUhuru: 'Fa Uhuru ho',
    version: 'Nkrataa',
    madeWith: 'Yɛdii ne',
    botswana: 'Botswana',
    saveChanges: 'Sie nsakrae no',
    settingsSaved: 'Wosii nhyehyɛe no',
    searchFaqs: 'Hwehwɛ Nsɛm...',
    close: 'To mu',
    image: 'Mfonini',
    upload: 'Fa kɔ',
    askMeAnything: 'Bisa me biribiara...',
    describeImage: 'Kyerɛ mfonini a wohia no',
    editingMessage: 'Sesa',
    micAccess: 'Hia Maekherofono',
    docLimit: 'Tokumente Dodow',
  },
  ga: {
    newChat: 'Nyemɔ foforɔ',
    search: 'Hewalɔ',
    settings: 'Hewale gbɔɔ',
    today: 'Gbɛkɛ',
    yesterday: 'Gbɛkɛ yɛ',
    older: 'Gbãŋ',
    signOut: 'Ba wɔ',
    searchPlaceholder: 'Hewalɔ nyemɔ...',
    noConversationsFound: 'Nyemɔ fɛɛ lɛ eba',
    searchResults: 'Hewalɔ Ŋutinya',
    greyedTeach: 'GreyEd Teach',
    uDocs: 'U Docs',
    adminDashboard: 'Admin Gbɔɔ',
    supaAdmin: 'Supa Admin',
    websiteBuilder: 'Website Wɔla',
    rename: 'Hiɔ foforɔ',
    delete: 'Ɖe',
    save: 'Dzra',
    cancel: 'Sɔ',
    account: 'Akaunti',
    language: 'Kɔɔ',
    privacy: 'Hintaŋ',
    help: 'Kpakpa',
    upgrade: 'Yɛ wo',
    subscription: 'Ntoatoaso',
    accountSettings: 'Akaunti gbɔɔ',
    name: 'Hiɔ',
    email: 'Imeila',
    changePassword: 'Tia mɔɔ',
    change: 'Tia',
    yourAccountEmail: 'Wo akaunti imeila',
    updateYourAccount: 'Tia wo akaunti mɔɔ fofo',
    languageSettings: 'Kɔɔ gbɔɔ',
    interfaceLanguage: 'Interface kɔɔ',
    controlsMenus: 'Edzi menu kple ŋɔli kɔɔ ŋu',
    defaultResponse: 'Kɔɔ shi Uhuru te yɛ shika',
    uhuruWillRespond: 'Uhuru te yɛ shika kɔɔ shi yɛ ŋ',
    helpSupport: 'Kpakpa & Kpee',
    contactSupport: 'Ka kyerɛ Kpee',
    needHelp: 'Ehia kpakpa? Yɛ kpee shi yɛ le afɔm.',
    contactUs: 'Ka kyerɛ yɛn',
    frequentlyAsked: 'Nsɛm shi wɔhe pii',
    noFaqsFound: 'Nsɛm fɛɛ eba',
    tryDifferent: 'Hewalɔ biribi fofo',
    aboutUhuru: 'Uhuru fa',
    version: 'Ɣeŋ',
    madeWith: 'Woyɛe kple',
    botswana: 'Botswana',
    saveChanges: 'Dzra tia',
    settingsSaved: 'Woɖo gbɔɔ ɖe eme',
    searchFaqs: 'Hewalɔ Nsɛm...',
    close: 'Xe',
    image: 'Mfonini',
    upload: 'Ɖe ŋu',
    askMeAnything: 'Ba mi biribi...',
    describeImage: 'Kyerɛ mfonini shi hia',
    editingMessage: 'Tia',
    micAccess: 'Hia Maekherofono',
    docLimit: 'Kadodo Sɔŋ',
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

const STORAGE_KEY_INTERFACE = 'uhuru-interface-language';
const STORAGE_KEY_RESPONSE = 'uhuru-response-language';

function readStoredLanguage(key: string): SupportedLanguage {
  try {
    const stored = localStorage.getItem(key);
    const valid: SupportedLanguage[] = ['english', 'setswana', 'french', 'twi', 'ewe', 'fante', 'ga'];
    if (stored && valid.includes(stored as SupportedLanguage)) {
      return stored as SupportedLanguage;
    }
  } catch {}
  return 'english';
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [interfaceLanguage, setInterfaceLanguageState] = useState<SupportedLanguage>(
    () => readStoredLanguage(STORAGE_KEY_INTERFACE)
  );
  const [responseLanguage, setResponseLanguageState] = useState<SupportedLanguage>(
    () => readStoredLanguage(STORAGE_KEY_RESPONSE)
  );

  const setInterfaceLanguage = useCallback((lang: SupportedLanguage) => {
    setInterfaceLanguageState(lang);
    try { localStorage.setItem(STORAGE_KEY_INTERFACE, lang); } catch {}
  }, []);

  const setResponseLanguage = useCallback((lang: SupportedLanguage) => {
    setResponseLanguageState(lang);
    try { localStorage.setItem(STORAGE_KEY_RESPONSE, lang); } catch {}
  }, []);

  const t = useCallback((key: string): string => {
    return (
      UI_TRANSLATIONS[interfaceLanguage]?.[key] ??
      UI_TRANSLATIONS.english[key] ??
      key
    );
  }, [interfaceLanguage]);

  return (
    <LanguageContext.Provider value={{ interfaceLanguage, responseLanguage, setInterfaceLanguage, setResponseLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
};
