/*
  # Add daily image count column to user profiles

  1. Database Changes
     - Add `daily_image_count` column to `user_profiles` table
     - Set default value to 0 for existing users
     - Allow null values for flexibility

  2. Purpose
     - Track daily image generation usage per user
     - Support rate limiting for image generation feature
     - Maintain consistency with existing daily_message_count pattern
*/

-- Add daily_image_count column to user_profiles table
ALTER TABLE user_profiles 
ADD COLUMN daily_image_count integer DEFAULT 0;

-- Add comment to describe the column
COMMENT ON COLUMN user_profiles.daily_image_count IS 'Number of images generated by user today (resets daily)';

-- Update existing users to have 0 daily image count
UPDATE user_profiles 
SET daily_image_count = 0 
WHERE daily_image_count IS NULL;